const { gql } = require("apollo-server");

const typeDefs = gql`
  type Query {
    "Fetch photos data for a specific location"
    photos(location: String!): AutogeneratedMainType
    "Fetch articles data for a specific location"
    articles(location: String!): AutogeneratedMainType
    "Fetch weather data for a specific location"
    weather(location: String, lat: String, lon: String): AutogeneratedMainType
  }

  type AutogeneratedMainType {
    results: [Results]
    articles: [Articles]
    list: [List]
  }

  "A photo array containing data of images and their authors"
  type Results {
    id: ID
    "Author who took the image"
    user: User
    "Url of the image"
    urls: Urls
  }

  "Url of the image in regular size"
  type Urls {
    regular: String
  }

  "Author of the image"
  type User {
    id: String
    "Username of author"
    username: String
    "Url to author's portfolio"
    portfolio_url: String
    "Profile image of author"
    profile_image: ProfileImage
  }

  "Url to profile image of author, type small"
  type ProfileImage {
    small: String
  }

  "An articles array containing data of articles and their sources"
  type Articles {
    "Title of the article"
    title: String
    "Short description of the article"
    description: String
    "Url to the full content of the article"
    url: String
    "Url to the thumbnail for the article"
    urlToImage: String
    "Time when the article was published, in UTC"
    publishedAt: String
    "Source of the article"
    source: Source
  }
  "Name of the article's source"
  type Source {
    name: String
  }

  type List {
    "Time of data forecasted, in UTC"
    dt_txt: String
    "Object for cloudiness"
    clouds: Clouds
    "Object for temperature and humidity"
    main: Main
  }

  type Main {
    "Temperature, in Celsius"
    temp: Float
    "Temerature accounts for the human perception of weather, in Celsius"
    feels_like: Float
    "Humidity, in %"
    humidity: Int
  }
  
  type Clouds {
    "Cloudiness, in %"
    all: Int
  }
`;

module.exports = typeDefs;
